version: "3.9"

services:
  web:
    container_name: backend_base
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules

